### ISSUE TITLE
hexagons shouls be squezed vertically, to the 5:4 ratio (bounding box)

### ISSUE THREAD

**Issue by judasMBit** [duzenko/webgame#3]
![image](https://user-images.githubusercontent.com/3994574/232533540-c139d2e3-9d88-4a2d-9f2a-4c860c8f6b3c.png)

**Comment by judasMBit** [comment]
I know, that the original HMM have them in a way that we have now,

![image](https://user-images.githubusercontent.com/3994574/232679034-c9f80ea7-350d-4104-b697-1ec8222ee65b.png)

but I'd like to give them more perspective view, like below

![image](https://user-images.githubusercontent.com/3994574/232678805-4b9b449d-2763-453a-a4a4-6b23d9cb5aa3.png)

**Comment by duzenko** [comment]
https://github.com/duzenko/webgame/commit/a03aa28aa915a900331e3388e78922b4270e70cb
![image](https://user-images.githubusercontent.com/1481807/232859566-82390d60-54da-4cec-9561-d65380038667.png)
