### ISSUE TITLE
Bug. Ranged unit can teleport to the enemy's dead body.

### ISSUE THREAD

**Issue by judasMBit** [duzenko/webgame#5]
![Screenshot 2023-04-30 17 12 48 - cropped](https://user-images.githubusercontent.com/3994574/235357947-a925f27a-254b-45c0-ac9b-2da2247b58d6.png)

**Comment by duzenko** [comment]
https://github.com/duzenko/webgame/commit/035bfd7f4af20dc4a8bc892166f8537f329ba6ca
